#import "../index.typ": template, tufted
#show: template.with(title: "Topological spaces")
#import "@preview/theorion:0.4.1": *
#import cosmos.rainbow: *
#show: show-theorion
#set text(
  font: (
    (name: "New Computer Modern", covers: "latin-in-cjk"), // 西文字体
  ),
  lang: "en",
)
#show math.equation: set text(font: (
  (name: "New Computer Modern Math", covers: "latin-in-cjk"), // 数学
))
#show raw: set text(
  font: (
    (name: "New Computer Modern", covers: "latin-in-cjk"), // 西文字体
  ),
  lang: "en",
)
#show math.equation: set text(features: ("cv01",))
#set par(leading: 0.9em)
#show heading.where(level: 1): set block(below: 2em, above: 2em)
#show heading.where(level: 2): set block(below: 1em, above: 2em)
#show heading.where(level: 3): set block(below: 1em, above: 2em)
#set math.equation(numbering: "(1)")
#show math.equation.where(block: true): it => {
  if not it.has("label") {
    let fields = it.fields()
    let _ = fields.remove("body")
    fields.numbering = none
    [#counter(math.equation).update(v => v - 1)#math.equation(..fields, it.body)<math-equation-without-label>]
  } else {
    it
  }
}
#let definition = definition.with(fill: blue.darken(10%))
#let proposition = proposition.with(fill: red.darken(10%))
#let lemma = lemma.with(fill: orange.darken(10%))
#set-inherited-levels(1)
#let leq = $lt.eq.slant$
#let eps = $epsilon$
#let int = $integral$
#let supp = $"supp"$
#let pd(f, x) = $frac(partial #f, partial #x)$
#let dd(f, x) = $frac(d #f, d #x)$

#let col(str) = text(fill: blue.darken(10%), weight: "bold", str)

#let col(content) = text(blue, content)
#let pd(f, x) = $frac(partial #f, partial #x)$

#let col(content) = text(blue, content)
#let pd(f, x) = $frac(partial #f, partial #x)$

= Chapter 2. Properties of Topological Spaces (Continued)

== 2.2. Countability and Separation Axioms

Recall two facts from analysis:
+ A point $x in RR^n$ is in the closure of $A$ if and only if there exists a sequence in $A$ converging to $x$.
+ Any sequence in $RR^n$ has at most one limit.

However, these two facts fail in general topological spaces.

#example[
  + Consider $RR$ with *#col("countable complement topology")*. Let $A=[0,1]$, then $-1 in overline(A)$ but $-1$ is not a limit of any sequence in $A$.
  + Consider $RR$ with *finite complement topology*. Then every point is a limit of the sequence $(1,2,3,...)$.
]

#definition(title: "neighborhood basis")[
  Given $x in X$. A set $cal(U) := {U_alpha}_(alpha in S)$ of neighborhoods of $x$ is called a *#col("neighborhood basis")* if for any neighborhood $U$ of $x$, there exists $U_alpha in cal(U)$ such that $x in U_alpha subset.eq U$.
]

#definition(title: "first & second countable")[
  + A space $(X, cal(T))$ is *#col("first-countable")* if every point $x in X$ has a countable neighborhood basis.
  + A space $(X, cal(T))$ is *#col("second-countable")* if the topology $cal(T)$ is generated by a countable basis.
]

#remark[
  *Second-countable* $==>$ *first-countable*.

  Any metric space is *first-countable* by taking $B(x, 1/n)$ as a neighborhood basis.
]

#example[(Discrete metric on $RR$)]
Let $X = RR$ with the metric:
$ d(x,y) = cases(0 ", "x=y, 1 ", "x != y) $
This metric induces the *discrete topology* on $RR$. This space is first-countable but *not* second-countable.

#lemma(title: "2.10")[
  Let $X$ be a topological space. If $x$ is a limit of a sequence in $A$, then $x in overline(A)$.
  The converse is true if $X$ is *first-countable*.
]

#proof[
  + Suppose $x$ is a limit of a sequence $(x_1, x_2, ...)$ in $A$. For any neighborhood $U$ of $x$, $U$ contains all but finitely many terms of the sequence. Hence $U inter A != emptyset$, which implies $x in overline(A)$.

  + Conversely, suppose $x in overline(A)$ and $X$ is first-countable. Let ${U_n}_(n=1)^infinity$ be a countable neighborhood basis of $x$.
    Define $V_n := inter.big_(i=1)^n U_i$, which are also open sets.
    Since $x in overline(A)$, for each $n$, $V_n inter A != emptyset$.
    Pick $x_n in V_n inter A$ to form a sequence $(x_1, x_2, ...)$.
    We claim $x_n -> x$. For any neighborhood $U$ of $x$, there exists some $U_N$ in the basis such that $U_N subset.eq U$. By construction, for all $n >= N$, $x_n in V_n subset.eq U_N subset.eq U$. Thus $U$ contains almost all terms.
]

#definition(title: "Hausdorff (T2)")[
  A space $X$ is *#col("Hausdorff")* (or $T_2$) if for any $x, y in X$ with $x != y$, there exist disjoint open sets $U, V$ such that $x in U$ and $y in V$.
]

#proposition[
  If $X$ is $T_2$, then any sequence in $X$ has at most one limit.
]

#proof[
  If not, assume $x != y$ are both limits of $(x_n)$. Since $X$ is $T_2$, there exist disjoint open sets $U$ and $V$ with $x in U$ and $y in V$.
  By the definition of limit, $U$ contains all but finitely many $x_n$, and $V$ also contains all but finitely many $x_n$.
  Hence $U inter V$ would contain almost all $x_n$, leading to a contradiction.
]

== 2.3. Continuous Maps

#definition(title: "embedding")[
  A map $f: X -> Y$ is an *#col("embedding")* if $f$ is a homeomorphism onto its image $f(X) subset.eq Y$.
  (i.e., $f$ is injective, continuous, and $f: X -> f(X)$ is a homeomorphism).
]

#example[(Interval embedding)]
The map $[0, 1) -> RR^2$ wrapping the interval is an example of embedding.

#example[(Disc homeomorphism)]
$D^n := {x in RR^n | |x| < 1}$. The map $f: D^n -> RR^n$ given by:

$ f(x) = frac(1, 1 - |x|^2) x $

is a homeomorphism.

#example[(Stereographic Projection)]
The map $P: S^n \\ {N} -> RR^n$ (where $N$ is the north pole) is a homeomorphism.

#lemma(title: "Characterization of Continuity")[
  Let $f: X -> Y$ be a map of topological spaces. The following are equivalent:
  + $f$ is continuous.
  + For any basis element $U$ in $Y$, $f^(-1)(U)$ is open.
  + For any subset $A subset.eq X$, $f(overline(A)) subset.eq overline(f(A))$.
  + For any closed set $V subset.eq Y$, $f^(-1)(V)$ is closed in $X$.
  + For any $x in X$ and any neighborhood $V$ of $f(x)$, there exists a neighborhood $U$ of $x$ such that $f(U) subset.eq V$.
]

#lemma(title: "Local Formulation of Continuity")[
  Let $X = union.big_alpha U_alpha$ where $U_alpha$ are open sets.
  $f: X -> Y$ is continuous if and only if $f|_{U_alpha}: U_alpha -> Y$ is continuous for each $alpha$.
]

#remark[This also holds if $X$ is a *finite* union of closed sets.]

#lemma(title: "Gluing Lemma")[
  Let ${A_i}$ be a collection of open subsets of $X$ covering $X$.
  Given continuous maps $f_i: A_i -> Y$ such that $f_i |_(A_i inter A_j) = f_j |_(A_i inter A_j)$,
  there exists a unique continuous map $f: union A_i -> Y$ such that $f |_(A_i) = f_i$.
]

== 2.4. Separation Axioms

#definition(title: "Separation Axioms")[
  + *#col("T_1")*: For any $x, y in X, x != y$, there exists a neighborhood $U$ of $x$ such that $y in.not U$.
  + *#col("T_2")*: $X$ is Hausdorff.
  + *#col("T_3 (Regular)")*: For any $x in X$ and closed set $V$ with $x in.not V$, there exist disjoint open sets $U, U'$ such that $x in U$ and $V subset.eq U'$.
  + *#col("T_4 (Normal)")*: For any disjoint closed sets $U_1, U_2$, there exist disjoint open sets $V_1, V_2$ such that $U_1 subset.eq V_1$ and $U_2 subset.eq V_2$.
]

#proposition[
  + $T_4 ==> T_3 ==> T_2 ==> T_1$.
  + Second-countable + $T_3 ==> T_4$ (Lindelöf Theorem).
]

#proposition[
  If $X$ is a metrizable space, then:
  + $X$ is first-countable.
  + $X$ satisfies separation axioms $T_1, T_2, T_3, T_4$.
]

#lemma(title: "Metric Space Properties")[
  Let $(X, d)$ be a metric space:
  + $x_n -> x$ in $X$ if and only if $lim_(n -> infinity) d(x, x_n) = 0$.
  + The metric $d: X times X -> RR$ is continuous.
  + For any $A subset.eq X$, $d_A(x) := inf_{y in A} d(x,y)$ is continuous.
  + $d_A^(-1)(0) = overline(A)$.
]

#proof(title: "proof of T4 of Metric Spaces")[
  For disjoint closed subsets $A, B$, we have $d_A(x) + d_B(x) > 0$.

  $ f(x) = frac(d_A(x), d_A(x) + d_B(x)) $

  $f$ is continuous, $f(A)=0$ and $f(B)=1$.
  Take $U = f^(-1)((-infinity, 1/3))$ and $V = f^(-1)((2/3, +infinity))$.
]

#theorem(title: "Urysohn Metrization Theorem")[
  Suppose $X$ satisfies $T_1, T_4$ and is second-countable, then $X$ is metrizable.
]

#lemma(title: "Urysohn's Lemma")[
  Suppose $X$ is $T_4$ (normal). For any two disjoint closed subsets $A, B subset.eq X$, there exists a continuous $f: X -> [0, 1]$ such that $f(A)=0, f(B)=1$.
]

= Chapter 3. Product

#definition(title: "Product Set")[
  As sets, $product_(alpha in S) A_alpha = { f: S -> union A_alpha | f(alpha) in A_alpha }$.
]

#definition(title: "Universal Property of Product")[
  For $A_alpha$ topological spaces, there exists a unique continuous map $f: B -> product A_alpha$ such that $p_beta compose f = f_beta$.
]

#definition(title: "disjoint union")[
  As sets, the *#col("disjoint union")* of a collection of sets ${A_alpha}_(alpha in S)$ is defined as:
  $ union.sq_(alpha in S) A_alpha = { (x, alpha) | alpha in S, x in A_alpha } $
]

#definition(title: "Universal Property of Coproduct")[
  For a collection of sets $A_alpha$, there exists a unique map $f: union.sq A_alpha -> B$ such that $f compose i_beta = f_beta$, where $i_beta: A_beta -> union.sq A_alpha$ is the canonical injection.
]
