#import "../index.typ": template, tufted
#show: template.with(title: "Topological spaces")
#import "@preview/theorion:0.4.1": *
#import cosmos.rainbow: *
#show: show-theorion
#set text(
  font: (
    (name: "New Computer Modern", covers: "latin-in-cjk"), // 西文字体
  ),
  lang: "en",
)
#show math.equation: set text(font: (
  (name: "New Computer Modern Math", covers: "latin-in-cjk"), // 数学
))
#show raw: set text(
  font: (
    (name: "New Computer Modern", covers: "latin-in-cjk"), // 西文字体
  ),
  lang: "en",
)
#show math.equation: set text(features: ("cv01",))
#set par(leading: 0.9em)
#show heading.where(level: 1): set block(below: 2em, above: 2em)
#show heading.where(level: 2): set block(below: 1em, above: 2em)
#show heading.where(level: 3): set block(below: 1em, above: 2em)
#set math.equation(numbering: "(1)")
#show math.equation.where(block: true): it => {
  if not it.has("label") {
    let fields = it.fields()
    let _ = fields.remove("body")
    fields.numbering = none
    [#counter(math.equation).update(v => v - 1)#math.equation(..fields, it.body)<math-equation-without-label>]
  } else {
    it
  }
}
#let definition = definition.with(fill: blue.darken(10%))
#let proposition = proposition.with(fill: red.darken(10%))
#let lemma = lemma.with(fill: orange.darken(10%))
#set-inherited-levels(1)
#let leq = $lt.eq.slant$
#let eps = $epsilon$
#let int = $integral$
#let supp = $"supp"$
#let pd(f, x) = $frac(partial #f, partial #x)$
#let dd(f, x) = $frac(d #f, d #x)$

#let col(str) = text(fill: blue.darken(10%), weight: "bold", str)

= Chapter 1. Topology

topological properties of *#col("spaces")* = remain uncharged under *#col("continuous")* deformation.

#definition(title: "topology")[
  Let $X$ be a set. A *#col("topology")* on $X$ is a subset $cal(T)subset.eq P(X)={A | A subset.eq X}$ such that:
  + $emptyset in cal(T), X in cal(T)$.

  + $U,V in cal(T) ==> U inter V in cal(T)$.(finite intersection)

  + $forall cal(S) subset.eq cal(T), union.big_(U in cal(S)) in cal(T)$.(arbitrary union)
  #remark[$cal(T)={"open sets in "X}$.]
  We say $(X, cal(T))$ is a *#col("topological space")*.

  If $U$ is open, we say $X\\ U$ is *#col("closed")*.
]

#definition(title: "continuous")[
  A map $f:X->Y$ between topological spaces is *#col("continuous")* if for any open set $U$ in $Y$, the preimage $f^(-1) (U)$ is open in $X$.
]
#definition(title: "homeomorphism")[
  A map $f:X->Y$ is a *#col("homeomorphism")* if it is a bijection and both $f$ and $f^(-1)$ are continuous.

  If such an $f$ exists, we say $X$ and $Y$ are *#col("homeomorphic")*.
]
#example[
  $f:[0,1)->S^1, t |-> e^(2 pi i t)$ is bijective and continuous, but not a homeomorphism since $f^(-1)$ is not continuous.
]

#example[
  $X$ is a set.

  + $cal(T)_"trivial" = {emptyset, X}$ "trivial topology"

  + $cal(T)_"discrete" = P(X)$ "discrete topology"

  + $cal(T)={U subset.eq X | X \\ U "either finite or" X}$ "finite complement topology"
]

#definition(title: "stronger & weaker")[
  Given two topologies $cal(T), cal(T)'$ on $X$,
  if $cal(T)' subset.eq cal(T)$, then we say $cal(T)$ is *#col("stronger")* or *#col("finer")* than $cal(T)'$, and $cal(T)'$ is *#col("weaker")* or *#col("coarser")* than $cal(T)$.
]

#definition(title: "subspace topology")[
  Let $(X, cal(T))$ be a topological space and $Y subset.eq X$ be a subset. The *#col("subspace topology")* on $Y$ is defined as $cal(T)_Y = {U inter Y | U in cal(T)}$.
]

#example[(most important) $X=RR^n$ with $U subset.eq RR^n$ is open if $forall x in U$, there exists $epsilon > 0$ such that $x in B_eps (x) subset.eq U$.]#footnote[$B_eps (x):={y | |x-y| < epsilon}$]

#definition(title: "basis of a topology")[
  Let $X$ be a set, a collection $cal(B)subset.eq P(X)$ is a *#col("basis")* for a topology if:
  + $forall x in X, exists U in cal(B), "s.t." x in U$.

  + $forall U,V in cal(B), forall x in U inter V, exists W in cal(B), "s.t." x in W subset.eq U inter V$.
]

#definition(title: "topology generated by a basis")[
  Given a basis $cal(B)$ on a set $X$, we can define a topology $cal(T)_cal(B)$ as:
  $ U in cal(T)_cal(B) <==> U=union.big_(V in cal(S)) V "for some" cal(S) subset.eq cal(B) $
]
#example[
  $X=RR^n$, $cal(B)={B_eps (x) | x in X, epsilon > 0}$, then $cal(T)_cal(B)$ is called the *#col("standard topology")* (or usual topology) on $RR^n$.
]

#definition(title: "metric")[
  A *#col("metric")* on a set $X$ is a map $d:X times X -> RR$ such that
  + $forall x,y in X, d(x,y) >= 0$ and $d(x,y)=0 <==> x=y$.

  + $forall x,y in X, d(x,y)=d(y,x)$.

  + $forall x,y,z in X, d(x,z) <= d(x,y)+d(y,z)$.
]

If $(X,d)$ is a metric space, then $cal(B)={B_eps (x) | x in X, epsilon > 0}$ defines a basis of a topology on $X$.

#definition(title: "normed vector space")[
  A *#col("normed vector space")* is a vector space $V$ over $FF=RR,CC "or" QQ$, with a norm function\
  $||dot||:V->RR$ such that
  + $forall v in V, ||v|| >= 0$ and $||v||=0 <==> v=0$.

  + $forall v in V, forall lambda in RR, ||lambda v|| = |lambda| ||v||$.

  + $forall u,v in V, ||u+v|| <= ||u|| + ||v||$.
]

$ "normed vector space" --> "metric space" --> "topological space" $

#example[Let $X={"continuous maps "f:[0,1]->RR}.$
  We can define different norms on $X$:
  + $C^0$-norm: $||f||_(C^0):= max_{t in [0,1]} |f(t)|$

  + $L^2$-norm: $||f||_(L^2):= sqrt(int_0^1 |f(x)|^2 "d"x)$
]

#example[
  $X=QQ$ and fix a prime $p$. Given $x in X$ with $x=p^k a/b, k,a,b in ZZ, p divides.not a, p divides.not b$. Define $||x||_p := p^(-k)$ and $||0||=0$, which is called "p-adic norm on $QQ$".
]

= Chapter 2. Properties of Topological Spaces
== 2.1. Interior and Closure
#definition[
  Let $A$ be a subset of $X$.
  + $U$ is a *#col("neighborhood")* of $x$ if $U$ is open and $A subset.eq U$.

  + We say $x$ is an *#col("interior point")* of $A$ if there exists a neighborhood of $x$ contained in $A$.
    We use $circle(A)$ to denote the set of interior points of $A$, which is called the *#col("interior")* of $A$.

  + We say $x$ is in the *#col("closure")* of $A$ if any neighborhood of $x$ intersects $A$.
    We use $overline(A)$ to denote the closure of $A$.

  + Note $circle(A)subset.eq A subset.eq overline(A)$.

    We use $partial A$ to denote $overline(A)\\circle(A)$, called the *#col("boundary")* of $A$.

  + A point $x$ is a *#col("limit point")* of $A$ if $x in overline(A\\{x})$.

  + A point $x$ is an *#col("isolated point")* of $A$ if $x in A$ but $x$ is *not* a limit point of $A$.

  + We say $A$ is *#col("dense")* in $X$ if $overline(A)=X$.
]

#example[$X=RR, A=[0,1), A'={"limit points of "A}.$

  - Suppose $RR$ has the standard topology, then $circle(A)=(0,1), overline(A)=[0,1], partial A={0,1}, A'=[0,1]$.

  - Suppose $RR$ has the finite complement topology, then $circle(A)=emptyset, overline(A)=partial A=A'=RR$.

  - Suppose $RR$ has the discrete topology, then $circle(A)=overline(A)=A, partial A=emptyset, A'=emptyset$.
]

#lemma(title: "2.6")[
  + $circle(A)=union.big_(U"open", U subset.eq A) U$.

  + $overline(A)=inter.big_(V"closed", A subset.eq V) V$.

  + $circle(A)$ is the largest open set contained in $A$.

    In particular, $A$ is open if and only if $circle(A)=A$.

  + $overline(A)$ is the smallest closed set containing $A$.

  + Let $A'={"limit points of" A}$, then $overline(A)=A union A'$.

    In particular, $A$ is closed $<==>$ $A' subset.eq A$ $<==>$ $A=overline(A)$.
]

#proof[
  + Let $V:= union.big_(U"open", U subset.eq A) U subset.eq A$.

    - $circle(A) subset.eq V$: $forall p in circle(A)$, by definition there exists an open neighborhood $U$ of $p$ contained in $A$, so $p in U subset.eq V$.

    - $V subset.eq circle(A)$: $forall p in V$, note $V$ is open, $p in V subset.eq A$ hence $p in circle(A)$.

  + Similar to 1.

  + By 1.

  + By 2.

  + Left to homework.

]

#definition(title: "limit of a sequence")[
  Let $(x_1,x_2,x_3,...)$ be a sequence of points in $X$. We say $x in X$ is a *#col("limit")* of the sequence if any neighborhood $U$ of $x$ contains all but finitely many points in the sequence.
]

#remark[
  A limit of a sequence $(x_1,x_2,...) !=$ A limit of the set ${x_1,x_2,...}$.

  #example[$(1,1,...)->1$ but ${1}$ has no limit points.]
]

Recall two facts from analysis:
+ A point $x in RR^n$ is in the closure of $A$ if and only if there exists a sequence in $A$ converging to $x$.

+ Any sequence in $RR^n$ has at most one limit.

However, these two facts fail in general topological spaces.

#example[
  + Consider $RR$ with *countable complement topology*. $A=[0,1]$, then $-1 in overline{A}$ but $-1$ is not a limit of any sequence in $A$.

  + Consider $RR$ with *finite complement topology*. Then every point is a limit of the sequence $(1,2,3,...)$.
]

#definition(title: "neighborhood basis")[
  Given $x in X$. A set $cal(U):={U_alpha}_(alpha in S)$ of neighborhoods of $x$ is called a *#col("neighborhood basis")* if for any neighborhood $U$ of $x$, there exists $U_alpha in cal(U)$ such that $x in U_alpha subset.eq U$.
]
